name: Documentation

on: [push, pull_request]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Update apt
      run: sudo apt-get update
    - name: Install apt deps
      run: sudo apt-get install -y libbluetooth-dev libusb-1.0-0-dev libgudev-1.0-dev unixodbc-dev libdbi-dev libdbd-sqlite3 libdbd-mysql libdbd-pgsql cmake cmake-data doxygen latexmk texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra graphviz
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: 3.14
    - name: Install Python deps
      run: pip install -r docs/manual/requirements.txt
    - name: Configure build
      run: ./configure
    - name: Build HTML docs
      run: make manual-html
    - name: Build PDF docs
      run: make manual-pdf
    - name: Collect
      run: |
        mkdir gh-pages
        cp -r build-configure/docs/manual/html/* gh-pages/
        cp build-configure/docs/manual/latex/*.pdf gh-pages/
    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: gh-pages


  # Deployment job
  deploy:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: docs
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
